application: gonawin-project
version: 1
runtime: go
api_version: go1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /ng
  static_files: static/index.html
  upload: static/index.html

- url: /static
  static_dir: static

- url: /templates
  static_dir: static/templates

- url: /a/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
  secure: always