application: gonawin-project
version: 1
runtime: go
api_version: go1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /
  static_files: app/index.html
  upload: app/index.html

- url: /app
  static_dir: app

- url: /templates
  static_dir: app/templates

- url: /a/.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
